services:
    app:
        environment:
            - ENVIRONMENT=development
        ports:
            - 9200:9200
    redis:
        ports:
            - 6379:6379

volumes:
    elasticsearch:

networks:
    cinema-network:
        name: cinema-network