services:
    elasticsearch:
        image: elasticsearch:8.2.2
        environment:
            - discovery.type=single-node
            - xpack.security.http.ssl.enabled=false
            - xpack.security.enabled=false
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        expose:
            - 9200
        ports:
            - 9200:9200
        networks:
          - cinema-network
        restart: unless-stopped
    redis:
        image: redis
        expose:
            - 6379
        ports:
            - 6379:6379
        networks:
          - cinema-network
        restart: unless-stopped

volumes:
    elasticsearch:

networks:
    cinema-network:
        name: cinema-network