services:
    app:
        container_name: app-test
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        environment:
            - ENVIRONMENT=testing
            - PYTHONUNBUFFERED=1
            - PYTHONDONTWRITEBYTECODE=1
            - REDIS_PATH=redis://redis:6379/0
            - ELASTIC_PATH=http://elasticsearch:9200
        env_file:
            - ./.env
        networks:
          - cinema-network
        restart: unless-stopped
    nginx:
        container_name: nginx-test
        build: ./infra/nginx
        ports:
            - 80:80
        depends_on:
            - app
        networks:
          - cinema-network
        restart: unless-stopped
    elasticsearch:
        container_name: elasticsearch-test
        image: elasticsearch:8.2.2
        environment:
            - discovery.type=single-node
            - xpack.security.http.ssl.enabled=false
            - xpack.security.enabled=false
        volumes:
            - elasticsearch-test:/usr/share/elasticsearch/data
        expose:
            - 9200
        ports:
            - 9200:9200
        networks:
          - cinema-network
        restart: unless-stopped
    redis:
        container_name: redis-test
        image: redis
        expose:
            - 6379
        ports:
            - 6379:6379
        networks:
          - cinema-network
        restart: unless-stopped

volumes:
    elasticsearch-test:

networks:
    cinema-network:
        name: cinema-network